#ifndef _public_H_
#define _public_H_

//开启标志位    
#define  extern power                _
#define  extern warm_A              
#define  extern warm_B               
#define  extern light                
#define  extern blowing              
#define  extern ventilate            
#define  extern warn                 
#define  extern buf                  

#define  extern digital_half         
#define  extern buzzer_flag          
#define  extern protect_flag         
#define  extern protect              
#define  extern night_flag          
#define  extern red_flag             
#define  extern night_light_flag     
#define  extern night                


#define  extern order_start          
#define  extern time_start           
#define  extern warm_ventilate       
#define  extern warm_ventilate_flag  
#define  extern warm_last            
#define  extern units_flag           
#define  extern link_flag 
#endif           